src.dir=src/main/java
web.dir=src/main/webapp
resources.dir=src/main/resources
test.dir=src/test/java
messages.dir=${resources.dir}

build.dir=build
classes.dir=${build.dir}/classes
jar.dir=${build.dir}/jar
lib.dir=lib

app.name=web_lab_3
app.version=1.0.0

main.class=org.example.bean.IndexBean
jar.name=${app.name}-${app.version}.jar
war.name=${app.name}-${app.version}.war

junit.jar=${lib.dir}/junit-4.13.2.jar
hamcrest.jar=${lib.dir}/hamcrest-core-1.3.jar
jsf.jar=${lib.dir}/jakarta.faces.jar
jpa.jar=${lib.dir}/jakarta.persistence.jar

music.file=C:/Users/nekru/IdeaProjects/web_lab_3/microwave.wav

server.user=s466853
server.host=se.ifmo.ru
server.port=2222
server.deploy.path=/home/studs/s466853/wildfly-26.1.3.Final/standalone/deployments/

svn.cmd=C:/Program Files/TortoiseSVN/bin/svn.exe