services:
  web1:
    #1: Не указан конкретный Dockerfile
    build: .
    ports:
      - "7813:5000"
    #2: Отсутствует политика перезапуска (restart)
    #3: Нет явного указания сетей
    #4: Нет переменных окружения (environment)


  web2:
    build: .
    ports:
      - "7814:5000"
    # Те же 4 плохие практики повторяются здесь
# Раздел networks отсутствует
# Все сервисы в одной сети по умолчанию и видят друг друга